name: 🐛 Bug Report
description: Report a bug in BudsyApp or the website
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the BudsyApp ecosystem is affected?
      options:
        - BudsyApp (iOS App)
        - BudsyApp iOS Purchase Log
        - BudsyApp iOS Journal Log
        - Website (budsy.app)
        - API/Backend
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - iOS Version: [e.g. 17.5]
        - BudsyApp Version: [e.g. 1.12]
        - Device: [e.g. iPhone 15 Pro]
        - Browser (if web): [e.g. Safari 17]
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgments
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the requested information
          required: true