name: ✨ Feature Request
description: Suggest a new feature or enhancement for BudsyApp
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand and evaluate your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the BudsyApp ecosystem would this feature affect?
      options:
        - BudsyApp (iOS App)
        - Website (budsy.app)
        - API/Backend
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement to existing feature
        - Integration with external service
        - User Interface improvement
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: "As a user, I want... so that..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific scenarios where this feature would be useful.
      placeholder: |
        1. When a user...
        2. If someone wants to...
        3. In the case where...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What should be true when this feature is complete?
      placeholder: |
        - [ ] User can...
        - [ ] The system should...
        - [ ] When X happens, Y should occur...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current workflows)
        - High (would significantly improve experience)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or workarounds?

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples from other apps.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, technical considerations, or related features.

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgments
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with BudsyApp's mission and target audience
          required: true